<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Theme creation
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */

function mesoffres_theme($existing, $type, $theme, $path)
{
  return [
    'mesoffres_table' => [
      'variables' => [
        'offres' => NULL,
        'administrateur' => NULL,
        'username' => NULL,
      ],
    ],
    'mail_notification' => [
      'template' => 'mail',
      'variables' => [
        'message' => NULL,
      ],
    ],
  ];
}

/**
 * Change first page after user login
 * @param $account
 */

function mesoffres_user_login($account)
{
  if (!isset($_GET['destination'])) {
    $response = new \Symfony\Component\HttpFoundation\RedirectResponse(\Drupal::url('mesoffres.list'));
    $response->send();
  }
}

function mesoffres_mail($key, &$message, $params)
{
  switch ($key) {
    case 'mail_notification':
      $message['from'] = Drupal::config('system.site')->get('mail');
      $message['header']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      $message['options'] = [];
      if (isset($params['options']) && !empty($params['options'])) {
        foreach ($params['options'] as $key => $value) {
          $message['options'][$key] = $value;
        }
      }
      break;
  }
}

function template_preprocess_mail_notification(&$variables)
{
  if (isset($variables['message']['options']) && !empty($variables['message']['options'])) {
    foreach ($variables['message']['options'] as $key => $value) {
      $variables[$key] = $value;
    }
  }
}

//function mesoffres_entity_insert(EntityInterface $entity) {
//
//  if ($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId() === 'node' && $entity->bundle() !== 'article')) {
//    return;
//  }
//
//  $mailManager = \Drupal::service('plugin.manager.mail');
//  $module = 'mesoffres';
//  $key = 'mail_notification';
//  $to = \Drupal::currentUser()->getEmail();
//  $params['message'] = $entity->get('body')->value;
//  $params['node_title'] = $entity->label();
//  $langcode = \Drupal::currentUser()->getPreferredLangcode();
//  $send = true;
//
//  $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
//  if ($result['result'] !== true) {
//    drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
//  } else {
//    drupal_set_message(t('Your message has been sent.'));
//  }
//
//}
